### ISSUE TITLE
Planning/schedule into Issues

### ISSUE THREAD

**Issue by PhilipeLouchtch** [steffansluis/DCSRoverScala#2]
Today we have composed a list of milestones. Even though I've never seen GitHub milestones work as well as hoped when creating them, let's give it a shot.

The milestones should be converted into GitHub milestones, project be setup, brief explanatory text added and some sort of time estimation done as well.

Then we can start discussions and categorize contributions by milestone.

**Comment by maikogoudriaan** [comment]
Milestones or more look a like issues are created

**Comment by PhilipeLouchtch** [comment]
Where?
